# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPlainTextEdit, QProgressBar, QPushButton, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_improMeasure(object):
    def setupUi(self, improMeasure):
        if not improMeasure.objectName():
            improMeasure.setObjectName(u"improMeasure")
        improMeasure.resize(1224, 758)
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(240, 240, 240, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(247, 247, 247, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(120, 120, 120, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(160, 160, 160, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        brush6 = QBrush(QColor(255, 255, 220, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        brush7 = QBrush(QColor(227, 227, 227, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        brush8 = QBrush(QColor(105, 105, 105, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        brush9 = QBrush(QColor(245, 245, 245, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        improMeasure.setPalette(palette)
        self.centralwidget = QWidget(improMeasure)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 10, 1201, 551))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        self.tabWidget.setPalette(palette1)
        self.tabWidget.setElideMode(Qt.ElideLeft)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tbSource = QWidget()
        self.tbSource.setObjectName(u"tbSource")
        self.pbBrowseRootdir = QPushButton(self.tbSource)
        self.pbBrowseRootdir.setObjectName(u"pbBrowseRootdir")
        self.pbBrowseRootdir.setGeometry(QRect(140, 50, 121, 31))
        self.edRootdir = QLineEdit(self.tbSource)
        self.edRootdir.setObjectName(u"edRootdir")
        self.edRootdir.setGeometry(QRect(270, 50, 651, 31))
        self.label = QLabel(self.tbSource)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 50, 111, 31))
        self.edConfig = QLineEdit(self.tbSource)
        self.edConfig.setObjectName(u"edConfig")
        self.edConfig.setGeometry(QRect(270, 100, 651, 31))
        self.label_3 = QLabel(self.tbSource)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 100, 111, 31))
        self.pbBrowseConfig = QPushButton(self.tbSource)
        self.pbBrowseConfig.setObjectName(u"pbBrowseConfig")
        self.pbBrowseConfig.setGeometry(QRect(140, 100, 121, 31))
        self.label_42 = QLabel(self.tbSource)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(30, 10, 131, 31))
        self.edCurrentDirectory = QLineEdit(self.tbSource)
        self.edCurrentDirectory.setObjectName(u"edCurrentDirectory")
        self.edCurrentDirectory.setEnabled(True)
        self.edCurrentDirectory.setGeometry(QRect(270, 10, 651, 31))
        self.edCurrentDirectory.setReadOnly(True)
        self.pbSave = QPushButton(self.tbSource)
        self.pbSave.setObjectName(u"pbSave")
        self.pbSave.setGeometry(QRect(30, 160, 121, 31))
        self.tabWidget.addTab(self.tbSource, "")
        self.tbCbCalib = QWidget()
        self.tbCbCalib.setObjectName(u"tbCbCalib")
        self.groupBox = QGroupBox(self.tbCbCalib)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 40, 1141, 471))
#if QT_CONFIG(statustip)
        self.groupBox.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.groupBox.setWhatsThis(u"")
#endif // QT_CONFIG(whatsthis)
        self.groupBox.setCheckable(False)
        self.pbCbCalibCalibCam = QPushButton(self.groupBox)
        self.pbCbCalibCalibCam.setObjectName(u"pbCbCalibCalibCam")
        self.pbCbCalibCalibCam.setGeometry(QRect(680, 60, 141, 41))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 51, 20))
        self.edCbCalibPsizeX = QLineEdit(self.groupBox)
        self.edCbCalibPsizeX.setObjectName(u"edCbCalibPsizeX")
        self.edCbCalibPsizeX.setGeometry(QRect(20, 50, 51, 26))
        self.edCbCalibPsizeY = QLineEdit(self.groupBox)
        self.edCbCalibPsizeY.setObjectName(u"edCbCalibPsizeY")
        self.edCbCalibPsizeY.setGeometry(QRect(20, 80, 51, 26))
        self.edCbCalibCsizeX = QLineEdit(self.groupBox)
        self.edCbCalibCsizeX.setObjectName(u"edCbCalibCsizeX")
        self.edCbCalibCsizeX.setGeometry(QRect(20, 140, 51, 26))
        self.edCbCalibCsizeY = QLineEdit(self.groupBox)
        self.edCbCalibCsizeY.setObjectName(u"edCbCalibCsizeY")
        self.edCbCalibCsizeY.setGeometry(QRect(20, 170, 51, 26))
        self.pbCbCalibFindcorners = QPushButton(self.groupBox)
        self.pbCbCalibFindcorners.setObjectName(u"pbCbCalibFindcorners")
        self.pbCbCalibFindcorners.setGeometry(QRect(680, 20, 141, 41))
        self.pbCbCalibMarkPrjpoints = QPushButton(self.groupBox)
        self.pbCbCalibMarkPrjpoints.setObjectName(u"pbCbCalibMarkPrjpoints")
        self.pbCbCalibMarkPrjpoints.setGeometry(QRect(680, 100, 141, 41))
        self.groupBox_4 = QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(830, 60, 301, 401))
        self.edCbCalibK6 = QLineEdit(self.groupBox_4)
        self.edCbCalibK6.setObjectName(u"edCbCalibK6")
        self.edCbCalibK6.setGeometry(QRect(180, 350, 111, 26))
        self.edCbCalibP1 = QLineEdit(self.groupBox_4)
        self.edCbCalibP1.setObjectName(u"edCbCalibP1")
        self.edCbCalibP1.setGeometry(QRect(180, 200, 111, 26))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(150, 110, 31, 20))
        self.label_15 = QLabel(self.groupBox_4)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(150, 260, 31, 20))
        self.label_17 = QLabel(self.groupBox_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(150, 320, 31, 20))
        self.label_18 = QLabel(self.groupBox_4)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(150, 350, 31, 20))
        self.edCbCalibFy = QLineEdit(self.groupBox_4)
        self.edCbCalibFy.setObjectName(u"edCbCalibFy")
        self.edCbCalibFy.setGeometry(QRect(180, 50, 111, 26))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(150, 140, 31, 20))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(150, 50, 31, 20))
        self.edCbCalibK4 = QLineEdit(self.groupBox_4)
        self.edCbCalibK4.setObjectName(u"edCbCalibK4")
        self.edCbCalibK4.setGeometry(QRect(180, 290, 111, 26))
        self.edCbCalibK2 = QLineEdit(self.groupBox_4)
        self.edCbCalibK2.setObjectName(u"edCbCalibK2")
        self.edCbCalibK2.setGeometry(QRect(180, 170, 111, 26))
        self.label_16 = QLabel(self.groupBox_4)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(150, 290, 31, 20))
        self.edCbCalibK1 = QLineEdit(self.groupBox_4)
        self.edCbCalibK1.setObjectName(u"edCbCalibK1")
        self.edCbCalibK1.setGeometry(QRect(180, 140, 111, 26))
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 230, 31, 20))
        self.edCbCalibFx = QLineEdit(self.groupBox_4)
        self.edCbCalibFx.setObjectName(u"edCbCalibFx")
        self.edCbCalibFx.setGeometry(QRect(180, 20, 111, 26))
        self.edCbCalibCx = QLineEdit(self.groupBox_4)
        self.edCbCalibCx.setObjectName(u"edCbCalibCx")
        self.edCbCalibCx.setGeometry(QRect(180, 80, 111, 26))
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(150, 170, 31, 20))
        self.edCbCalibCy = QLineEdit(self.groupBox_4)
        self.edCbCalibCy.setObjectName(u"edCbCalibCy")
        self.edCbCalibCy.setGeometry(QRect(180, 110, 111, 26))
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(150, 200, 31, 20))
        self.edCbCalibK3 = QLineEdit(self.groupBox_4)
        self.edCbCalibK3.setObjectName(u"edCbCalibK3")
        self.edCbCalibK3.setGeometry(QRect(180, 260, 111, 26))
        self.label_5 = QLabel(self.groupBox_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(150, 20, 31, 20))
        self.edCbCalibP2 = QLineEdit(self.groupBox_4)
        self.edCbCalibP2.setObjectName(u"edCbCalibP2")
        self.edCbCalibP2.setGeometry(QRect(180, 230, 111, 26))
        self.edCbCalibK5 = QLineEdit(self.groupBox_4)
        self.edCbCalibK5.setObjectName(u"edCbCalibK5")
        self.edCbCalibK5.setGeometry(QRect(180, 320, 111, 26))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(150, 80, 31, 20))
        self.label_61 = QLabel(self.groupBox_4)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(10, 60, 31, 20))
        self.label_58 = QLabel(self.groupBox_4)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(10, 120, 31, 20))
        self.label_56 = QLabel(self.groupBox_4)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 90, 31, 20))
        self.edCbCalibTy = QLineEdit(self.groupBox_4)
        self.edCbCalibTy.setObjectName(u"edCbCalibTy")
        self.edCbCalibTy.setGeometry(QRect(30, 150, 111, 26))
        self.edCbCalibRx = QLineEdit(self.groupBox_4)
        self.edCbCalibRx.setObjectName(u"edCbCalibRx")
        self.edCbCalibRx.setGeometry(QRect(30, 30, 111, 26))
        self.edCbCalibRz = QLineEdit(self.groupBox_4)
        self.edCbCalibRz.setObjectName(u"edCbCalibRz")
        self.edCbCalibRz.setGeometry(QRect(30, 90, 111, 26))
        self.edCbCalibRy = QLineEdit(self.groupBox_4)
        self.edCbCalibRy.setObjectName(u"edCbCalibRy")
        self.edCbCalibRy.setGeometry(QRect(30, 60, 111, 26))
        self.edCbCalibTz = QLineEdit(self.groupBox_4)
        self.edCbCalibTz.setObjectName(u"edCbCalibTz")
        self.edCbCalibTz.setGeometry(QRect(30, 180, 111, 26))
        self.label_57 = QLabel(self.groupBox_4)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(10, 180, 31, 20))
        self.label_59 = QLabel(self.groupBox_4)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(10, 30, 31, 20))
        self.edCbCalibTx = QLineEdit(self.groupBox_4)
        self.edCbCalibTx.setObjectName(u"edCbCalibTx")
        self.edCbCalibTx.setGeometry(QRect(30, 120, 111, 26))
        self.label_60 = QLabel(self.groupBox_4)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(10, 150, 31, 20))
        self.label_38 = QLabel(self.groupBox)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 120, 61, 21))
        self.edCbCalibSrcDir = QLineEdit(self.groupBox)
        self.edCbCalibSrcDir.setObjectName(u"edCbCalibSrcDir")
        self.edCbCalibSrcDir.setGeometry(QRect(100, 50, 561, 26))
        self.label_39 = QLabel(self.groupBox)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(100, 30, 331, 20))
        self.label_40 = QLabel(self.groupBox)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(100, 80, 331, 40))
        self.pbCbCalibUndistort = QPushButton(self.groupBox)
        self.pbCbCalibUndistort.setObjectName(u"pbCbCalibUndistort")
        self.pbCbCalibUndistort.setGeometry(QRect(680, 140, 141, 41))
        self.pteCbCalibSrcPhotos = QPlainTextEdit(self.groupBox)
        self.pteCbCalibSrcPhotos.setObjectName(u"pteCbCalibSrcPhotos")
        self.pteCbCalibSrcPhotos.setGeometry(QRect(100, 110, 561, 87))
        self.pteCbCalibSrcPhotos.setReadOnly(True)
        self.label_44 = QLabel(self.groupBox)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 210, 61, 21))
        self.edCbCalibFlags = QLineEdit(self.groupBox)
        self.edCbCalibFlags.setObjectName(u"edCbCalibFlags")
        self.edCbCalibFlags.setGeometry(QRect(20, 230, 51, 26))
        self.progressCbCalib = QProgressBar(self.groupBox)
        self.progressCbCalib.setObjectName(u"progressCbCalib")
        self.progressCbCalib.setGeometry(QRect(20, 430, 791, 23))
        self.progressCbCalib.setValue(1)
        self.edCbCalibImgHeight = QLineEdit(self.groupBox)
        self.edCbCalibImgHeight.setObjectName(u"edCbCalibImgHeight")
        self.edCbCalibImgHeight.setGeometry(QRect(20, 340, 61, 26))
        self.edCbCalibImgHeight.setReadOnly(True)
        self.edCbCalibImgWidth = QLineEdit(self.groupBox)
        self.edCbCalibImgWidth.setObjectName(u"edCbCalibImgWidth")
        self.edCbCalibImgWidth.setGeometry(QRect(20, 290, 61, 26))
        self.edCbCalibImgWidth.setReadOnly(True)
        self.label_43 = QLabel(self.groupBox)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(10, 270, 101, 21))
        self.label_45 = QLabel(self.groupBox)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(10, 320, 101, 21))
        self.cmbCbCalibCam = QComboBox(self.tbCbCalib)
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.addItem("")
        self.cmbCbCalibCam.setObjectName(u"cmbCbCalibCam")
        self.cmbCbCalibCam.setGeometry(QRect(10, 10, 201, 26))
        self.cmbCbCalibCam.setMaxVisibleItems(7)
        self.cmbCbCalibCam.setMaxCount(7)
        self.tabWidget.addTab(self.tbCbCalib, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(230, 20, 421, 20))
        self.label_37 = QLabel(self.tab)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 50, 151, 31))
        self.pbBrowseSiCalibBgimg = QPushButton(self.tab)
        self.pbBrowseSiCalibBgimg.setObjectName(u"pbBrowseSiCalibBgimg")
        self.pbBrowseSiCalibBgimg.setGeometry(QRect(150, 50, 91, 31))
        self.edSiCalibBgImg = QLineEdit(self.tab)
        self.edSiCalibBgImg.setObjectName(u"edSiCalibBgImg")
        self.edSiCalibBgImg.setGeometry(QRect(250, 50, 411, 31))
        self.edSiCalibBgImg.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(830, 100, 351, 401))
        self.edSiCalibK5 = QLineEdit(self.groupBox_3)
        self.edSiCalibK5.setObjectName(u"edSiCalibK5")
        self.edSiCalibK5.setGeometry(QRect(210, 330, 111, 26))
        self.label_27 = QLabel(self.groupBox_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(180, 180, 31, 20))
        self.label_29 = QLabel(self.groupBox_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(180, 30, 31, 20))
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(180, 360, 31, 20))
        self.edSiCalibFy = QLineEdit(self.groupBox_3)
        self.edSiCalibFy.setObjectName(u"edSiCalibFy")
        self.edSiCalibFy.setGeometry(QRect(210, 60, 111, 26))
        self.edSiCalibTy = QLineEdit(self.groupBox_3)
        self.edSiCalibTy.setObjectName(u"edSiCalibTy")
        self.edSiCalibTy.setGeometry(QRect(50, 150, 111, 26))
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(180, 240, 31, 20))
        self.edSiCalibK2 = QLineEdit(self.groupBox_3)
        self.edSiCalibK2.setObjectName(u"edSiCalibK2")
        self.edSiCalibK2.setGeometry(QRect(210, 180, 111, 26))
        self.edSiCalibK1 = QLineEdit(self.groupBox_3)
        self.edSiCalibK1.setObjectName(u"edSiCalibK1")
        self.edSiCalibK1.setGeometry(QRect(210, 150, 111, 26))
        self.edSiCalibK6 = QLineEdit(self.groupBox_3)
        self.edSiCalibK6.setObjectName(u"edSiCalibK6")
        self.edSiCalibK6.setGeometry(QRect(210, 360, 111, 26))
        self.edSiCalibTx = QLineEdit(self.groupBox_3)
        self.edSiCalibTx.setObjectName(u"edSiCalibTx")
        self.edSiCalibTx.setGeometry(QRect(50, 120, 111, 26))
        self.label_32 = QLabel(self.groupBox_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(20, 150, 31, 20))
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(180, 330, 31, 20))
        self.edSiCalibFx = QLineEdit(self.groupBox_3)
        self.edSiCalibFx.setObjectName(u"edSiCalibFx")
        self.edSiCalibFx.setGeometry(QRect(210, 30, 111, 26))
        self.edSiCalibTz = QLineEdit(self.groupBox_3)
        self.edSiCalibTz.setObjectName(u"edSiCalibTz")
        self.edSiCalibTz.setGeometry(QRect(50, 180, 111, 26))
        self.edSiCalibP2 = QLineEdit(self.groupBox_3)
        self.edSiCalibP2.setObjectName(u"edSiCalibP2")
        self.edSiCalibP2.setGeometry(QRect(210, 240, 111, 26))
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(180, 270, 31, 20))
        self.edSiCalibRz = QLineEdit(self.groupBox_3)
        self.edSiCalibRz.setObjectName(u"edSiCalibRz")
        self.edSiCalibRz.setGeometry(QRect(50, 90, 111, 26))
        self.edSiCalibP1 = QLineEdit(self.groupBox_3)
        self.edSiCalibP1.setObjectName(u"edSiCalibP1")
        self.edSiCalibP1.setGeometry(QRect(210, 210, 111, 26))
        self.label_36 = QLabel(self.groupBox_3)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(20, 60, 31, 20))
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(180, 300, 31, 20))
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(180, 150, 31, 20))
        self.label_31 = QLabel(self.groupBox_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 90, 31, 20))
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(180, 120, 31, 20))
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(180, 60, 31, 20))
        self.label_28 = QLabel(self.groupBox_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(180, 210, 31, 20))
        self.edSiCalibRy = QLineEdit(self.groupBox_3)
        self.edSiCalibRy.setObjectName(u"edSiCalibRy")
        self.edSiCalibRy.setGeometry(QRect(50, 60, 111, 26))
        self.label_30 = QLabel(self.groupBox_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(180, 90, 31, 20))
        self.edSiCalibK3 = QLineEdit(self.groupBox_3)
        self.edSiCalibK3.setObjectName(u"edSiCalibK3")
        self.edSiCalibK3.setGeometry(QRect(210, 270, 111, 26))
        self.label_33 = QLabel(self.groupBox_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(20, 180, 31, 20))
        self.edSiCalibK4 = QLineEdit(self.groupBox_3)
        self.edSiCalibK4.setObjectName(u"edSiCalibK4")
        self.edSiCalibK4.setGeometry(QRect(210, 300, 111, 26))
        self.edSiCalibCy = QLineEdit(self.groupBox_3)
        self.edSiCalibCy.setObjectName(u"edSiCalibCy")
        self.edSiCalibCy.setGeometry(QRect(210, 120, 111, 26))
        self.label_34 = QLabel(self.groupBox_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 120, 31, 20))
        self.edSiCalibRx = QLineEdit(self.groupBox_3)
        self.edSiCalibRx.setObjectName(u"edSiCalibRx")
        self.edSiCalibRx.setGeometry(QRect(50, 30, 111, 26))
        self.label_35 = QLabel(self.groupBox_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 30, 31, 20))
        self.edSiCalibCx = QLineEdit(self.groupBox_3)
        self.edSiCalibCx.setObjectName(u"edSiCalibCx")
        self.edSiCalibCx.setGeometry(QRect(210, 90, 111, 26))
        self.pbSiCalibRead = QPushButton(self.tab)
        self.pbSiCalibRead.setObjectName(u"pbSiCalibRead")
        self.pbSiCalibRead.setGeometry(QRect(20, 130, 141, 41))
        self.pbSiCalibCalib = QPushButton(self.tab)
        self.pbSiCalibCalib.setObjectName(u"pbSiCalibCalib")
        self.pbSiCalibCalib.setGeometry(QRect(20, 390, 141, 41))
        self.label_62 = QLabel(self.tab)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(180, 140, 141, 21))
        self.label_63 = QLabel(self.tab)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(30, 180, 141, 21))
        self.edSiCalibFlags = QLineEdit(self.tab)
        self.edSiCalibFlags.setObjectName(u"edSiCalibFlags")
        self.edSiCalibFlags.setGeometry(QRect(150, 180, 111, 26))
        self.label_46 = QLabel(self.tab)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(20, 90, 151, 31))
        self.pbBrowseSiCalibBgimg_2 = QPushButton(self.tab)
        self.pbBrowseSiCalibBgimg_2.setObjectName(u"pbBrowseSiCalibBgimg_2")
        self.pbBrowseSiCalibBgimg_2.setGeometry(QRect(150, 90, 91, 31))
        self.edSiCalibObjpointsXlsfile = QLineEdit(self.tab)
        self.edSiCalibObjpointsXlsfile.setObjectName(u"edSiCalibObjpointsXlsfile")
        self.edSiCalibObjpointsXlsfile.setGeometry(QRect(250, 90, 241, 31))
        self.edSiCalibObjpointsXlsfile.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.cmbSiCalibCam = QComboBox(self.tab)
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.addItem("")
        self.cmbSiCalibCam.setObjectName(u"cmbSiCalibCam")
        self.cmbSiCalibCam.setGeometry(QRect(20, 20, 201, 26))
        self.cmbSiCalibCam.setMaxVisibleItems(7)
        self.cmbSiCalibCam.setMaxCount(7)
        self.edSiCalibObjpointsXlssheet = QLineEdit(self.tab)
        self.edSiCalibObjpointsXlssheet.setObjectName(u"edSiCalibObjpointsXlssheet")
        self.edSiCalibObjpointsXlssheet.setGeometry(QRect(500, 90, 241, 31))
        self.edSiCalibObjpointsXlssheet.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.pushButton = QPushButton(self.tab_5)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(60, 130, 211, 29))
        self.cmbImagesCam = QComboBox(self.tab_5)
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.addItem("")
        self.cmbImagesCam.setObjectName(u"cmbImagesCam")
        self.cmbImagesCam.setGeometry(QRect(20, 20, 201, 26))
        self.cmbImagesCam.setMaxVisibleItems(7)
        self.cmbImagesCam.setMaxCount(7)
        self.edImagesFiles = QLineEdit(self.tab_5)
        self.edImagesFiles.setObjectName(u"edImagesFiles")
        self.edImagesFiles.setGeometry(QRect(100, 70, 481, 26))
        self.label_214 = QLabel(self.tab_5)
        self.label_214.setObjectName(u"label_214")
        self.label_214.setGeometry(QRect(30, 70, 63, 20))
        self.pteImagesList = QPlainTextEdit(self.tab_5)
        self.pteImagesList.setObjectName(u"pteImagesList")
        self.pteImagesList.setGeometry(QRect(770, 70, 381, 321))
        self.pteImagesList.setReadOnly(True)
        self.lbImagesList = QLabel(self.tab_5)
        self.lbImagesList.setObjectName(u"lbImagesList")
        self.lbImagesList.setGeometry(QRect(770, 40, 231, 20))
        self.pbImagesRefreshList = QPushButton(self.tab_5)
        self.pbImagesRefreshList.setObjectName(u"pbImagesRefreshList")
        self.pbImagesRefreshList.setGeometry(QRect(600, 70, 111, 30))
        self.pushButton_4 = QPushButton(self.tab_5)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 200, 211, 29))
        self.tabWidget.addTab(self.tab_5, "")
        self.tbPoints = QWidget()
        self.tbPoints.setObjectName(u"tbPoints")
        self.pushButton_2 = QPushButton(self.tbPoints)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 30, 121, 29))
        self.tabWidget.addTab(self.tbPoints, "")
        self.tbSurfaces = QWidget()
        self.tbSurfaces.setObjectName(u"tbSurfaces")
        self.tabWidget.addTab(self.tbSurfaces, "")
        self.tbUtils = QWidget()
        self.tbUtils.setObjectName(u"tbUtils")
        self.tabWidgetUtils = QTabWidget(self.tbUtils)
        self.tabWidgetUtils.setObjectName(u"tabWidgetUtils")
        self.tabWidgetUtils.setGeometry(QRect(12, 20, 1171, 491))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Active, QPalette.AlternateBase, brush3)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Midlight, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.Dark, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Inactive, QPalette.Shadow, brush8)
        palette2.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush9)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette2.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette2.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush9)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.tabWidgetUtils.setPalette(palette2)
        self.tabWidgetUtils.setAutoFillBackground(False)
        self.tabWidgetUtils.setDocumentMode(False)
        self.tbUtils_preview = QWidget()
        self.tbUtils_preview.setObjectName(u"tbUtils_preview")
        self.pbPreviewSelectPics = QPushButton(self.tbUtils_preview)
        self.pbPreviewSelectPics.setObjectName(u"pbPreviewSelectPics")
        self.pbPreviewSelectPics.setGeometry(QRect(10, 20, 141, 41))
        self.lbPreviewImshow = QLabel(self.tbUtils_preview)
        self.lbPreviewImshow.setObjectName(u"lbPreviewImshow")
        self.lbPreviewImshow.setGeometry(QRect(380, 60, 701, 381))
        self.lbPreviewImshow.setFrameShape(QFrame.Box)
        self.lbPreviewImshow.setFrameShadow(QFrame.Plain)
        self.lbPreviewSrcDir = QLabel(self.tbUtils_preview)
        self.lbPreviewSrcDir.setObjectName(u"lbPreviewSrcDir")
        self.lbPreviewSrcDir.setGeometry(QRect(160, 30, 201, 21))
        self.lbPreviewSrcDir.setFrameShape(QFrame.Box)
        self.cmbPreviewSrcPics = QComboBox(self.tbUtils_preview)
        self.cmbPreviewSrcPics.setObjectName(u"cmbPreviewSrcPics")
        self.cmbPreviewSrcPics.setGeometry(QRect(380, 30, 701, 26))
        font = QFont()
        font.setPointSize(7)
        self.cmbPreviewSrcPics.setFont(font)
        self.tabWidgetUtils.addTab(self.tbUtils_preview, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.edFileListWildcardInput = QLineEdit(self.tab_3)
        self.edFileListWildcardInput.setObjectName(u"edFileListWildcardInput")
        self.edFileListWildcardInput.setGeometry(QRect(200, 20, 291, 26))
        self.label_7 = QLabel(self.tab_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 20, 171, 21))
        self.pteFileListDisplay = QPlainTextEdit(self.tab_3)
        self.pteFileListDisplay.setObjectName(u"pteFileListDisplay")
        self.pteFileListDisplay.setGeometry(QRect(50, 140, 1081, 301))
        self.lbFileListFileCountAll = QLabel(self.tab_3)
        self.lbFileListFileCountAll.setObjectName(u"lbFileListFileCountAll")
        self.lbFileListFileCountAll.setGeometry(QRect(530, 110, 271, 21))
        self.lbFileListCountExisted = QLabel(self.tab_3)
        self.lbFileListCountExisted.setObjectName(u"lbFileListCountExisted")
        self.lbFileListCountExisted.setGeometry(QRect(800, 110, 321, 21))
        self.label_41 = QLabel(self.tab_3)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(30, 70, 171, 21))
        self.edFileListCstyleInput = QLineEdit(self.tab_3)
        self.edFileListCstyleInput.setObjectName(u"edFileListCstyleInput")
        self.edFileListCstyleInput.setGeometry(QRect(200, 70, 291, 26))
        self.edFileListCstyleStart = QLineEdit(self.tab_3)
        self.edFileListCstyleStart.setObjectName(u"edFileListCstyleStart")
        self.edFileListCstyleStart.setGeometry(QRect(200, 100, 141, 26))
        self.edFileListCstyleCount = QLineEdit(self.tab_3)
        self.edFileListCstyleCount.setObjectName(u"edFileListCstyleCount")
        self.edFileListCstyleCount.setGeometry(QRect(350, 100, 141, 26))
        self.pbFileListDisplayWildcard = QPushButton(self.tab_3)
        self.pbFileListDisplayWildcard.setObjectName(u"pbFileListDisplayWildcard")
        self.pbFileListDisplayWildcard.setGeometry(QRect(500, 20, 111, 29))
        self.pbFileListDisplayCstyle = QPushButton(self.tab_3)
        self.pbFileListDisplayCstyle.setObjectName(u"pbFileListDisplayCstyle")
        self.pbFileListDisplayCstyle.setGeometry(QRect(500, 70, 111, 29))
        self.tabWidgetUtils.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pbMassTracking = QPushButton(self.tab_2)
        self.pbMassTracking.setObjectName(u"pbMassTracking")
        self.pbMassTracking.setGeometry(QRect(40, 40, 241, 29))
        self.pbFeatureMatch = QPushButton(self.tab_2)
        self.pbFeatureMatch.setObjectName(u"pbFeatureMatch")
        self.pbFeatureMatch.setGeometry(QRect(40, 240, 161, 29))
        self.pbOpticalFlow = QPushButton(self.tab_2)
        self.pbOpticalFlow.setObjectName(u"pbOpticalFlow")
        self.pbOpticalFlow.setGeometry(QRect(40, 130, 161, 29))
        self.pbTemplateMatch = QPushButton(self.tab_2)
        self.pbTemplateMatch.setObjectName(u"pbTemplateMatch")
        self.pbTemplateMatch.setGeometry(QRect(40, 160, 161, 29))
        self.pbEcc = QPushButton(self.tab_2)
        self.pbEcc.setObjectName(u"pbEcc")
        self.pbEcc.setGeometry(QRect(40, 190, 161, 29))
        self.pbVideoFrameCount = QPushButton(self.tab_2)
        self.pbVideoFrameCount.setObjectName(u"pbVideoFrameCount")
        self.pbVideoFrameCount.setGeometry(QRect(300, 40, 241, 29))
        self.tabWidgetUtils.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pbMlGridSlice = QPushButton(self.tab_4)
        self.pbMlGridSlice.setObjectName(u"pbMlGridSlice")
        self.pbMlGridSlice.setGeometry(QRect(20, 10, 151, 29))
        self.tabWidgetUtils.addTab(self.tab_4, "")
        self.tabWidget.addTab(self.tbUtils, "")
        self.pteMsg = QPlainTextEdit(self.centralwidget)
        self.pteMsg.setObjectName(u"pteMsg")
        self.pteMsg.setGeometry(QRect(120, 570, 1071, 121))
        self.pteMsg.setReadOnly(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 570, 81, 31))
        self.pbClearMsg = QPushButton(self.centralwidget)
        self.pbClearMsg.setObjectName(u"pbClearMsg")
        self.pbClearMsg.setGeometry(QRect(10, 600, 93, 29))
        self.progress = QProgressBar(self.centralwidget)
        self.progress.setObjectName(u"progress")
        self.progress.setGeometry(QRect(10, 640, 101, 23))
        self.progress.setValue(100)
        improMeasure.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(improMeasure)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1224, 26))
        improMeasure.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(improMeasure)
        self.statusbar.setObjectName(u"statusbar")
        improMeasure.setStatusBar(self.statusbar)

        self.retranslateUi(improMeasure)

        self.tabWidget.setCurrentIndex(6)
        self.cmbCbCalibCam.setCurrentIndex(0)
        self.cmbSiCalibCam.setCurrentIndex(0)
        self.cmbImagesCam.setCurrentIndex(0)
        self.tabWidgetUtils.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(improMeasure)
    # setupUi

    def retranslateUi(self, improMeasure):
        improMeasure.setWindowTitle(QCoreApplication.translate("improMeasure", u"ImPro Measure prototype", None))
#if QT_CONFIG(whatsthis)
        self.tabWidget.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.pbBrowseRootdir.setText(QCoreApplication.translate("improMeasure", u"Browse ...", None))
        self.edRootdir.setText(QCoreApplication.translate("improMeasure", u"D:/yuansen/ImPro/improMeasure/examples/2022brb2c56", None))
        self.label.setText(QCoreApplication.translate("improMeasure", u"Root directory", None))
        self.label_3.setText(QCoreApplication.translate("improMeasure", u"Config file", None))
        self.pbBrowseConfig.setText(QCoreApplication.translate("improMeasure", u"Browse ...", None))
        self.label_42.setText(QCoreApplication.translate("improMeasure", u"Current directory", None))
        self.pbSave.setText(QCoreApplication.translate("improMeasure", u"Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbSource), QCoreApplication.translate("improMeasure", u"Basic Info", None))
        self.groupBox.setTitle(QCoreApplication.translate("improMeasure", u"Calibration by Chessboard Images", None))
        self.pbCbCalibCalibCam.setText(QCoreApplication.translate("improMeasure", u"Calibrate camera", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("improMeasure", u"pSize", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibPsizeX.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along x", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibPsizeX.setText(QCoreApplication.translate("improMeasure", u"7", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibPsizeY.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibPsizeY.setText(QCoreApplication.translate("improMeasure", u"7", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibCsizeX.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x (distance between corners)", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibCsizeX.setText(QCoreApplication.translate("improMeasure", u"50.8", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibCsizeY.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along y (distance between corners)", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibCsizeY.setText(QCoreApplication.translate("improMeasure", u"50.8", None))
#if QT_CONFIG(tooltip)
        self.pbCbCalibFindcorners.setToolTip(QCoreApplication.translate("improMeasure", u"Finds chessboard corners. Writes corner coordinates to the sheet 'Chessboard_Calib' of outputs.xlsx. Pictures with corners drawn will be saved to [chessboard filename]_corners.JPG.", None))
#endif // QT_CONFIG(tooltip)
        self.pbCbCalibFindcorners.setText(QCoreApplication.translate("improMeasure", u"Find corners", None))
#if QT_CONFIG(tooltip)
        self.pbCbCalibMarkPrjpoints.setToolTip(QCoreApplication.translate("improMeasure", u"Generate images with projected corners", None))
#endif // QT_CONFIG(tooltip)
        self.pbCbCalibMarkPrjpoints.setText(QCoreApplication.translate("improMeasure", u"Mark projection", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("improMeasure", u"Camera parameters", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibK6.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibP1.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_10.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_10.setText(QCoreApplication.translate("improMeasure", u"cy", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_15.setText(QCoreApplication.translate("improMeasure", u"k3", None))
#if QT_CONFIG(tooltip)
        self.label_17.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_17.setText(QCoreApplication.translate("improMeasure", u"k5", None))
#if QT_CONFIG(tooltip)
        self.label_18.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_18.setText(QCoreApplication.translate("improMeasure", u"k6", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibFy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_11.setText(QCoreApplication.translate("improMeasure", u"k1", None))
#if QT_CONFIG(tooltip)
        self.label_8.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_8.setText(QCoreApplication.translate("improMeasure", u"fy", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibK4.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibK2.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_16.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_16.setText(QCoreApplication.translate("improMeasure", u"k4", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibK1.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_14.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_14.setText(QCoreApplication.translate("improMeasure", u"p2", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibFx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibCx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_12.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_12.setText(QCoreApplication.translate("improMeasure", u"k2", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibCy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_13.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_13.setText(QCoreApplication.translate("improMeasure", u"p1", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibK3.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_5.setText(QCoreApplication.translate("improMeasure", u"fx", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibP2.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibK5.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_9.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_9.setText(QCoreApplication.translate("improMeasure", u"cx", None))
#if QT_CONFIG(tooltip)
        self.label_61.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_61.setText(QCoreApplication.translate("improMeasure", u"ry", None))
#if QT_CONFIG(tooltip)
        self.label_58.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_58.setText(QCoreApplication.translate("improMeasure", u"tx", None))
#if QT_CONFIG(tooltip)
        self.label_56.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_56.setText(QCoreApplication.translate("improMeasure", u"rz", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibTy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibRx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibRz.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibRy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edCbCalibTz.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_57.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_57.setText(QCoreApplication.translate("improMeasure", u"tz", None))
#if QT_CONFIG(tooltip)
        self.label_59.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_59.setText(QCoreApplication.translate("improMeasure", u"rx", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibTx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_60.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_60.setText(QCoreApplication.translate("improMeasure", u"ty", None))
#if QT_CONFIG(tooltip)
        self.label_38.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_38.setText(QCoreApplication.translate("improMeasure", u"cell size", None))
#if QT_CONFIG(tooltip)
        self.label_39.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_39.setText(QCoreApplication.translate("improMeasure", u"Source Photo Directory", None))
#if QT_CONFIG(tooltip)
        self.label_40.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_40.setText(QCoreApplication.translate("improMeasure", u"Source Photos", None))
#if QT_CONFIG(tooltip)
        self.pbCbCalibUndistort.setToolTip(QCoreApplication.translate("improMeasure", u"Generate images with projected corners", None))
#endif // QT_CONFIG(tooltip)
        self.pbCbCalibUndistort.setText(QCoreApplication.translate("improMeasure", u"Undistort photos", None))
#if QT_CONFIG(tooltip)
        self.label_44.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_44.setText(QCoreApplication.translate("improMeasure", u"flags", None))
#if QT_CONFIG(tooltip)
        self.edCbCalibFlags.setToolTip(QCoreApplication.translate("improMeasure", u"Suggestions:\n"
"            0: OpenCV default (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3)\n"
"            16385: (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6)\n"
"            24705: (calibrates fx, fy, cx, cy, k1, k2, p1, p2,   , k4, k5)\n"
"            129: (calibrates fx, fy, cx, cy, k1, k2, p1, p2)\n"
"            193: (calibrates fx, fy, cx, cy, k1, p1, p2)\n"
"            201: (calibrates fx, fy, cx, cy, k1)\n"
"            205: (calibrates fx, fy, k1)\n"
"            207: (calibrates fx, k1)\n"
"-----------------------------------\n"
"Definition of flags:\n"
"          cv.CALIB_USE_INTRINSIC_GUESS = 0x00001,\n"
"          cv.CALIB_FIX_ASPECT_RATIO = 0x00002,\n"
"          cv.CALIB_FIX_PRINCIPAL_POINT = 0x00004,\n"
"          cv.CALIB_ZERO_TANGENT_DIST = 0x00008,\n"
"          cv.CALIB_FIX_FOCAL_LENGTH = 0x00010,\n"
"          cv.CALIB_FIX_K1 = 0x00020,\n"
"          cv.CALIB_FIX_K2 = 0x00040,\n"
"          cv.CALIB_FIX_K3 = 0x00080,\n"
"          cv.CALIB_FIX_K4 = 0x00800,\n"
"        "
                        "  cv.CALIB_FIX_K5 = 0x01000,\n"
"          cv.CALIB_FIX_K6 = 0x02000,\n"
"          cv.CALIB_RATIONAL_MODEL = 0x04000,\n"
"          cv.CALIB_THIN_PRISM_MODEL = 0x08000,\n"
"          cv.CALIB_FIX_S1_S2_S3_S4 = 0x10000,\n"
"          cv.CALIB_TILTED_MODEL = 0x40000,\n"
"          cv.CALIB_FIX_TAUX_TAUY = 0x80000,\n"
"          cv.CALIB_USE_QR = 0x100000,\n"
"          cv.CALIB_FIX_TANGENT_DIST = 0x200000,\n"
"          cv.CALIB_FIX_INTRINSIC = 0x00100,\n"
"          cv.CALIB_SAME_FOCAL_LENGTH = 0x00200,\n"
"          cv.CALIB_ZERO_DISPARITY = 0x00400,\n"
"          cv.CALIB_USE_LU = (1 << 17),\n"
"          cv.CALIB_USE_EXTRINSIC_GUESS = (1 << 22)", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibFlags.setText("")
#if QT_CONFIG(tooltip)
        self.edCbCalibImgHeight.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along y (distance between corners)", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibImgHeight.setText("")
#if QT_CONFIG(tooltip)
        self.edCbCalibImgWidth.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x (distance between corners)", None))
#endif // QT_CONFIG(tooltip)
        self.edCbCalibImgWidth.setText("")
#if QT_CONFIG(tooltip)
        self.label_43.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_43.setText(QCoreApplication.translate("improMeasure", u"image width", None))
#if QT_CONFIG(tooltip)
        self.label_45.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners  along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_45.setText(QCoreApplication.translate("improMeasure", u"image height", None))
        self.cmbCbCalibCam.setItemText(0, QCoreApplication.translate("improMeasure", u"Temporary", None))
        self.cmbCbCalibCam.setItemText(1, QCoreApplication.translate("improMeasure", u"Camera 1", None))
        self.cmbCbCalibCam.setItemText(2, QCoreApplication.translate("improMeasure", u"Camera 2", None))
        self.cmbCbCalibCam.setItemText(3, QCoreApplication.translate("improMeasure", u"Camera 3", None))
        self.cmbCbCalibCam.setItemText(4, QCoreApplication.translate("improMeasure", u"Camera 4", None))
        self.cmbCbCalibCam.setItemText(5, QCoreApplication.translate("improMeasure", u"Camera 5", None))
        self.cmbCbCalibCam.setItemText(6, QCoreApplication.translate("improMeasure", u"Camera 6", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbCbCalib), QCoreApplication.translate("improMeasure", u"Chessboard Calib", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tbCbCalib), QCoreApplication.translate("improMeasure", u"Chessboard Calibration", None))
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("improMeasure", u"Source: Worksheet [SingleImageCalib] in the configuration file", None))
        self.label_37.setText(QCoreApplication.translate("improMeasure", u"Background image", None))
        self.pbBrowseSiCalibBgimg.setText(QCoreApplication.translate("improMeasure", u"Browse ...", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("improMeasure", u"Camera parameters", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibK5.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_27.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_27.setText(QCoreApplication.translate("improMeasure", u"k2", None))
#if QT_CONFIG(tooltip)
        self.label_29.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_29.setText(QCoreApplication.translate("improMeasure", u"fx", None))
#if QT_CONFIG(tooltip)
        self.label_22.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_22.setText(QCoreApplication.translate("improMeasure", u"k6", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibFy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibTy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_26.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_26.setText(QCoreApplication.translate("improMeasure", u"p2", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibK2.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibK1.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibK6.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibTx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_32.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_32.setText(QCoreApplication.translate("improMeasure", u"ty", None))
#if QT_CONFIG(tooltip)
        self.label_21.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_21.setText(QCoreApplication.translate("improMeasure", u"k5", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibFx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibTz.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibP2.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_20.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_20.setText(QCoreApplication.translate("improMeasure", u"k3", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibRz.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibP1.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_36.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_36.setText(QCoreApplication.translate("improMeasure", u"ry", None))
#if QT_CONFIG(tooltip)
        self.label_25.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_25.setText(QCoreApplication.translate("improMeasure", u"k4", None))
#if QT_CONFIG(tooltip)
        self.label_23.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_23.setText(QCoreApplication.translate("improMeasure", u"k1", None))
#if QT_CONFIG(tooltip)
        self.label_31.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_31.setText(QCoreApplication.translate("improMeasure", u"rz", None))
#if QT_CONFIG(tooltip)
        self.label_19.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_19.setText(QCoreApplication.translate("improMeasure", u"cy", None))
#if QT_CONFIG(tooltip)
        self.label_24.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_24.setText(QCoreApplication.translate("improMeasure", u"fy", None))
#if QT_CONFIG(tooltip)
        self.label_28.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_28.setText(QCoreApplication.translate("improMeasure", u"p1", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibRy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_30.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_30.setText(QCoreApplication.translate("improMeasure", u"cx", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibK3.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_33.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_33.setText(QCoreApplication.translate("improMeasure", u"tz", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibK4.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.edSiCalibCy.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_34.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_34.setText(QCoreApplication.translate("improMeasure", u"tx", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibRx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label_35.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_35.setText(QCoreApplication.translate("improMeasure", u"rx", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibCx.setToolTip(QCoreApplication.translate("improMeasure", u"number of corners along y", None))
#endif // QT_CONFIG(tooltip)
        self.pbSiCalibRead.setText(QCoreApplication.translate("improMeasure", u"Read points", None))
        self.pbSiCalibCalib.setText(QCoreApplication.translate("improMeasure", u"Calibrate camera", None))
#if QT_CONFIG(tooltip)
        self.label_62.setToolTip(QCoreApplication.translate("improMeasure", u"physical size of a cell along x and y", None))
#endif // QT_CONFIG(tooltip)
        self.label_62.setText(QCoreApplication.translate("improMeasure", u"0 calibration points", None))
#if QT_CONFIG(tooltip)
        self.label_63.setToolTip(QCoreApplication.translate("improMeasure", u"        The flags for the calibration. See OpenCV documentation of \n"
"        calibrateCamera() for definition of flags.\n"
"        Important: For non-planar calibration rigs the initial intrinsic \n"
"        matrix must be specified (See OpenCV documentation). That is, the \n"
"        flag CALIB_USE_INTRINSIC_GUESS (1) must be enabled, that is, the \n"
"        flags must be an odd (cannot be zero or any other even)\n"
"        Typical values are: \n"
"            0: OpenCV default (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3)\n"
"            16385: (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6)\n"
"            24705: (calibrates fx, fy, cx, cy, k1, k2, p1, p2,   , k4, k5)\n"
"            129: (calibrates fx, fy, cx, cy, k1, k2, p1, p2)\n"
"            193: (calibrates fx, fy, cx, cy, k1, p1, p2)\n"
"            201: (calibrates fx, fy, cx, cy, k1)\n"
"            205: (calibrates fx, fy, k1)\n"
"            207: (calibrates fx, k1)\n"
"            To remove CALIB_USE_INTRINSIC_GUESS (if y"
                        "ou do not want to guess\n"
"            the camera matrix), use the above number minus 1. For example,\n"
"            give 206 (i.e., 207 - 1) to calibrate fx and k1 without using \n"
"            initial guess camera matrix.", None))
#endif // QT_CONFIG(tooltip)
        self.label_63.setText(QCoreApplication.translate("improMeasure", u"Calibration Flags", None))
#if QT_CONFIG(tooltip)
        self.edSiCalibFlags.setToolTip(QCoreApplication.translate("improMeasure", u"        The flags for the calibration. See OpenCV documentation of \n"
"        calibrateCamera() for definition of flags.\n"
"        Important: For non-planar calibration rigs the initial intrinsic \n"
"        matrix must be specified (See OpenCV documentation). That is, the \n"
"        flag CALIB_USE_INTRINSIC_GUESS (1) must be enabled, that is, the \n"
"        flags must be an odd (cannot be zero or any other even)\n"
"        Typical values are: \n"
"            0: OpenCV default (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3)\n"
"            16385: (calibrates fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, k5, k6)\n"
"            24705: (calibrates fx, fy, cx, cy, k1, k2, p1, p2,   , k4, k5)\n"
"            129: (calibrates fx, fy, cx, cy, k1, k2, p1, p2)\n"
"            193: (calibrates fx, fy, cx, cy, k1, p1, p2)\n"
"            201: (calibrates fx, fy, cx, cy, k1)\n"
"            205: (calibrates fx, fy, k1)\n"
"            207: (calibrates fx, k1)\n"
"            To remove CALIB_USE_INTRINSIC_GUESS (if y"
                        "ou do not want to guess\n"
"            the camera matrix), use the above number minus 1. For example,\n"
"            give 206 (i.e., 207 - 1) to calibrate fx and k1 without using \n"
"            initial guess camera matrix.", None))
#endif // QT_CONFIG(tooltip)
        self.edSiCalibFlags.setText(QCoreApplication.translate("improMeasure", u"193", None))
        self.label_46.setText(QCoreApplication.translate("improMeasure", u"Object points", None))
        self.pbBrowseSiCalibBgimg_2.setText(QCoreApplication.translate("improMeasure", u"Browse ...", None))
        self.cmbSiCalibCam.setItemText(0, QCoreApplication.translate("improMeasure", u"Temporary", None))
        self.cmbSiCalibCam.setItemText(1, QCoreApplication.translate("improMeasure", u"Camera 1", None))
        self.cmbSiCalibCam.setItemText(2, QCoreApplication.translate("improMeasure", u"Camera 2", None))
        self.cmbSiCalibCam.setItemText(3, QCoreApplication.translate("improMeasure", u"Camera 3", None))
        self.cmbSiCalibCam.setItemText(4, QCoreApplication.translate("improMeasure", u"Camera 4", None))
        self.cmbSiCalibCam.setItemText(5, QCoreApplication.translate("improMeasure", u"Camera 5", None))
        self.cmbSiCalibCam.setItemText(6, QCoreApplication.translate("improMeasure", u"Camera 6", None))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("improMeasure", u"Single Image Calib", None))
#if QT_CONFIG(tooltip)
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("improMeasure", u"Single image calibration", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton.setText(QCoreApplication.translate("improMeasure", u"Load from config file", None))
        self.cmbImagesCam.setItemText(0, QCoreApplication.translate("improMeasure", u"Temporary", None))
        self.cmbImagesCam.setItemText(1, QCoreApplication.translate("improMeasure", u"Camera 1", None))
        self.cmbImagesCam.setItemText(2, QCoreApplication.translate("improMeasure", u"Camera 2", None))
        self.cmbImagesCam.setItemText(3, QCoreApplication.translate("improMeasure", u"Camera 3", None))
        self.cmbImagesCam.setItemText(4, QCoreApplication.translate("improMeasure", u"Camera 4", None))
        self.cmbImagesCam.setItemText(5, QCoreApplication.translate("improMeasure", u"Camera 5", None))
        self.cmbImagesCam.setItemText(6, QCoreApplication.translate("improMeasure", u"Camera 6", None))

#if QT_CONFIG(tooltip)
        self.edImagesFiles.setToolTip(QCoreApplication.translate("improMeasure", u"d:/pix/DSC*.JPG\n"
"d:/pix/DSC%02d.JPG , 2, 5  (start, count) \n"
"d:/pix/DSC%02d.JPG , 2, 8, 2  (start, end, increment)", None))
#endif // QT_CONFIG(tooltip)
        self.label_214.setText(QCoreApplication.translate("improMeasure", u"Files", None))
        self.lbImagesList.setText(QCoreApplication.translate("improMeasure", u"List of files (0 files)", None))
        self.pbImagesRefreshList.setText(QCoreApplication.translate("improMeasure", u"Refresh List", None))
        self.pushButton_4.setText(QCoreApplication.translate("improMeasure", u"Save to config file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("improMeasure", u"Images", None))
        self.pushButton_2.setText(QCoreApplication.translate("improMeasure", u"PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbPoints), QCoreApplication.translate("improMeasure", u"Points", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbSurfaces), QCoreApplication.translate("improMeasure", u"Surfaces", None))
#if QT_CONFIG(tooltip)
        self.tabWidgetUtils.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.pbPreviewSelectPics.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.pbPreviewSelectPics.setText(QCoreApplication.translate("improMeasure", u"Select source pics ...", None))
        self.lbPreviewImshow.setText(QCoreApplication.translate("improMeasure", u"Preview", None))
        self.lbPreviewSrcDir.setText(QCoreApplication.translate("improMeasure", u"Source directory", None))
        self.tabWidgetUtils.setTabText(self.tabWidgetUtils.indexOf(self.tbUtils_preview), QCoreApplication.translate("improMeasure", u"Preview", None))
#if QT_CONFIG(tooltip)
        self.tabWidgetUtils.setTabToolTip(self.tabWidgetUtils.indexOf(self.tbUtils_preview), QCoreApplication.translate("improMeasure", u"Preview Pictures", None))
#endif // QT_CONFIG(tooltip)
        self.edFileListWildcardInput.setText(QCoreApplication.translate("improMeasure", u"examples\\2022steelf\\*.jpg", None))
        self.label_7.setText(QCoreApplication.translate("improMeasure", u"File names with wildcard", None))
        self.pteFileListDisplay.setPlainText("")
        self.lbFileListFileCountAll.setText(QCoreApplication.translate("improMeasure", u"Number of files:", None))
        self.lbFileListCountExisted.setText(QCoreApplication.translate("improMeasure", u"Number of existed files", None))
        self.label_41.setText(QCoreApplication.translate("improMeasure", u"File names in C style", None))
        self.edFileListCstyleInput.setText(QCoreApplication.translate("improMeasure", u"examples\\2022steelf\\221109_FUJI_L_%05d.jpg", None))
        self.edFileListCstyleStart.setText(QCoreApplication.translate("improMeasure", u"1", None))
        self.edFileListCstyleCount.setText(QCoreApplication.translate("improMeasure", u"20", None))
        self.pbFileListDisplayWildcard.setText(QCoreApplication.translate("improMeasure", u"Display files", None))
        self.pbFileListDisplayCstyle.setText(QCoreApplication.translate("improMeasure", u"Display files", None))
        self.tabWidgetUtils.setTabText(self.tabWidgetUtils.indexOf(self.tab_3), QCoreApplication.translate("improMeasure", u"File List", None))
        self.pbMassTracking.setText(QCoreApplication.translate("improMeasure", u"Mass Tracking using Optical Flow", None))
        self.pbFeatureMatch.setText(QCoreApplication.translate("improMeasure", u"Feature match", None))
        self.pbOpticalFlow.setText(QCoreApplication.translate("improMeasure", u"Optical flow", None))
        self.pbTemplateMatch.setText(QCoreApplication.translate("improMeasure", u"Template match", None))
        self.pbEcc.setText(QCoreApplication.translate("improMeasure", u"Ecc", None))
        self.pbVideoFrameCount.setText(QCoreApplication.translate("improMeasure", u"Video frame count", None))
        self.tabWidgetUtils.setTabText(self.tabWidgetUtils.indexOf(self.tab_2), QCoreApplication.translate("improMeasure", u"Mass Tracking", None))
        self.pbMlGridSlice.setText(QCoreApplication.translate("improMeasure", u"Grid Slice", None))
        self.tabWidgetUtils.setTabText(self.tabWidgetUtils.indexOf(self.tab_4), QCoreApplication.translate("improMeasure", u"ML Utils", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbUtils), QCoreApplication.translate("improMeasure", u"Utilities", None))
        self.label_4.setText(QCoreApplication.translate("improMeasure", u"Messages", None))
        self.pbClearMsg.setText(QCoreApplication.translate("improMeasure", u"Clear", None))
    # retranslateUi

