# The following program is revised by a program that was 
# generated by Bing chat given:
"""
 "Use python matplotlib, write a function that plots 3D scatter points, 
 given a N by 3 numpy array, where N is number of points, and each row 
 is the coordinates of a point. If any coordinate of a point is an 
 numpy.nan, skip the point. "
 (2023-03-30)
"""
 
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

   
def test_plot_3d_scatter_points(points):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    mask = np.isnan(points).any(axis=1)
    ax.scatter(points[~mask][:,0], points[~mask][:,1], points[~mask][:,2])
    ax.set_xlabel('X axis (x = 0, .86, 1.36, 1.86, ..., 20.86 m')
    ax.set_ylabel('Y axis (y = 6, 9, 12, ..., 20.25 m')
    ax.set_zlabel('Z axis (z = 14.49, 13.49, ..., 0.49 m')
    plt.show()