#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 26, 2025 11:09:35 AM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import converter_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1055x742+451+28")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="#000000")

        self.top = top

        self.ed_cel = tk.Entry(self.top)
        self.ed_cel.place(relx=0.047, rely=0.067, height=60, relwidth=0.25)
        self.ed_cel.configure(background="white")
        self.ed_cel.configure(disabledforeground="#a3a3a3")
        self.ed_cel.configure(font="TkFixedFont")
        self.ed_cel.configure(foreground="#000000")
        self.ed_cel.configure(highlightbackground="#d9d9d9")
        self.ed_cel.configure(highlightcolor="#000000")
        self.ed_cel.configure(insertbackground="#000000")
        self.ed_cel.configure(selectbackground="#d9d9d9")
        self.ed_cel.configure(selectforeground="black")
        self.ed_cel.bind('<KeyRelease>',lambda e:converter_support.on_click_ed_cel(e, self))

        self.ed_fah = tk.Text(self.top)
        self.ed_fah.place(relx=0.038, rely=0.216, relheight=0.085, relwidth=0.26)

        self.ed_fah.configure(background="white")
        self.ed_fah.configure(font="TkTextFont")
        self.ed_fah.configure(foreground="black")
        self.ed_fah.configure(highlightbackground="#d9d9d9")
        self.ed_fah.configure(highlightcolor="#000000")
        self.ed_fah.configure(insertbackground="#000000")
        self.ed_fah.configure(selectbackground="#d9d9d9")
        self.ed_fah.configure(selectforeground="black")
        self.ed_fah.configure(wrap="word")
        self.ed_fah.bind('<KeyRelease>',lambda e:converter_support.on_click_ed_fah(e, self))

        self.bt_clear = tk.Button(self.top)
        self.bt_clear.place(relx=0.057, rely=0.416, height=66, width=237)
        self.bt_clear.configure(activebackground="#d9d9d9")
        self.bt_clear.configure(activeforeground="black")
        self.bt_clear.configure(background="#d9d9d9")
        self.bt_clear.configure(cursor="fleur")
        self.bt_clear.configure(disabledforeground="#a3a3a3")
        self.bt_clear.configure(foreground="#000000")
        self.bt_clear.configure(highlightbackground="#d9d9d9")
        self.bt_clear.configure(highlightcolor="#000000")
        self.bt_clear.configure(text='''Clear''')
        self.bt_clear.bind('<ButtonRelease-1>',lambda e:converter_support.on_click_bt_clear(e, self))

def start_up():
    converter_support.main()

if __name__ == '__main__':
    converter_support.main()




