#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    May 26, 2025 03:15:31 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import test1

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = test1.Toplevel1(_top1)
    root.mainloop()

def on_click_clear(*args):
    if _debug:
        print('test1_support.on_click_clear')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def on_key_cel(*args):
    if _debug:
        print('test1_support.on_key_cel')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

def on_key_fah(*args):
    if _debug:
        print('test1_support.on_key_fah')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()

if __name__ == '__main__':
    test1.start_up()




